# Generated by Django 5.0.6 on 2024-05-24 03:52

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    operations = [
        migrations.RunSQL("CREATE SCHEMA IF NOT EXISTS sample_schema;"),
    ]
